

services:
  bank_db:
    container_name: bank_db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_pass
      POSTGRES_DB: bank_db
    volumes:
      - bank_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  bank_db:



