#
# application.yml — главный конфигурационный файл Spring Boot.


#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: secret_pass
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.current_session_context_class: thread
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog.yml
    default-schema: public

jwt:
  secret-key: "a3366ab389a1d7b3f1fbcad97c499bb976294ef24c38e6c2472ac866167727bc"
  key-timelife: 1800000

server:
  port: 8080